development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:033803ef3750ef7e38497dfc24a5b1fd@hammerjaw.redistogo.com:9227/
  channel_prefix: myapp_production
